meta_product_name: "Cofetăria cu laborator propriu Irina"
meta_title: "Gustul copilăriei? Doar la noi!"
meta_description: "Cofetăria cu laborator propriu Irina din Bacău vă oferă prăjituri, torturi, produse tradiționale (cozonaci, pască, colaci) și multe altele..."
meta_image: "https://res.cloudinary.com/dqbu9lypc/image/upload/v1614928547/4xwa0sy4dars1bdxsrpmnfq0qibj.png"
twitter_account: "@ursaqe"